- name: Hello World Sample
  hosts: all
  remote_user: techadmin
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: run the shell command
      shell: echo "HelloWorld"
    - name: copy one file to another
      copy:
        src: /home/techmadmin/Desktop/test.txt 
        dest: /tmp/
        owner: awx
        group: awx
        mode: 0644
