- name: Hello World Sample
  hosts: all
  remote_user: awx
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: run the shell command
      shell: echo "HelloWorld"
    - name: copy one file to another
      copy:
        src: /home/techmadmin/documents/sample.txt 
        dest: /tmp/
        owner: awx
        group: awx
        remote_src: no
    - file:
       path: /home/techmadmin/ssn
       state: directory
       mode: 0755
    - file:
       path: /tmp/ssn
       state: directory
       mode: 0755
