- name: Hello World Sample
  hosts: all
  remote_user: techadmin
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: run the shell command
      shell: echo "HelloWorld"
    - name: copy one file to another
      copy:
        src: /root/samplefiles/testsample.yml 
        dest: /tmp/
        remote_src: no
